name: Adding to queue

on:
  pull_request:
    types:
      [
        opened,
        synchronize,
        reopened,
        ready_for_review,
        review_requested,
        labeled,
        unlabeled,
      ]
  issue_comment:
    types: [created, edited]
  workflow_dispatch:

jobs:
  add_to_queue:
    env:
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Slack Merge Queue
        uses: lwhiteley/slack-merge-queue@v2.0.0
        id: add_to_q
        with:
          mode: "INIT"
          channel: "automate-deploy-queue"
          init_trigger: "/merging"

      - name: Get the output
        run: echo "stauts => ${{ steps.add_to_q.outputs.status }}"
