name: Slack Notification

on:
  issue_comment:
    types: [created]
jobs:
  notify_slack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Notify Slack
        if: github.event.issue.pull_request
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          COMMENT_CONTENT=$(jq -r .comment.body "${{ github.event_path }}")
          PAYLOAD="{\"text\": \"New comment on Pull Request ${{ github.event.issue.number }} by ${{ github.event.comment.user.login }}: \n\n${COMMENT_CONTENT}\"}"
          curl -X POST -H 'Content-type: application/json' --data "${PAYLOAD}" $SLACK_WEBHOOK_URL
